const app=document.querySelector('#app');
const state={route:location.hash.slice(1)||'home',theme:localStorage.theme||'dark',user:JSON.parse(localStorage.getItem('tcf-user')||'null'),module:'Listening',test:1,mode:'review',q:0,answers:{},flagged:new Set()};
const questions=[
 {level:'A1',prompt:'ÉTUDIANTS INTERNATIONAUX : NE RESTEZ PAS SEULS !\nInscrivez-vous dans l’association de l’Université pour discuter avec des étudiants français, participer à des groupes de conversation et faire des activités ensemble.',ask:'Que propose cette association ?',answers:['Des cours particuliers','Des jobs pendant le week-end','Des rencontres entre jeunes','Des voyages à l’étranger'],correct:2},
 {level:'A1',prompt:'Le train pour Lyon partira exceptionnellement voie 8 avec un retard de dix minutes.',ask:'Que doivent faire les voyageurs ?',answers:['Changer de quai','Acheter un billet','Attendre une heure','Prendre un autobus'],correct:0},
 {level:'A2',prompt:'Bonjour Léa, je serai en retard au dîner. Commencez sans moi, j’arrive vers vingt heures trente.',ask:'Pourquoi cette personne écrit-elle ?',answers:['Pour annuler un rendez-vous','Pour prévenir d’un retard','Pour changer de restaurant','Pour inviter une amie'],correct:1},
 {level:'B1',prompt:'La mairie ouvre une nouvelle médiathèque samedi. Les inscriptions seront gratuites pendant tout le week-end.',ask:'Quelle information est annoncée ?',answers:['Une fermeture temporaire','Un tarif réduit','Une inauguration','Un changement d’adresse'],correct:2},
 {level:'B2',prompt:'Selon l’étude, les salariés qui organisent de courtes pauses régulières maintiennent plus longtemps leur concentration.',ask:'Que recommande implicitement cette étude ?',answers:['De travailler chez soi','De raccourcir la journée','De faire des pauses','De changer de métier'],correct:2}
];
function setTheme(){document.documentElement.dataset.theme=state.theme;localStorage.theme=state.theme}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function go(route){location.hash=route}
function nav(minimal=false){return `<nav class="nav"><button class="brand" onclick="go('${state.user?'dashboard':'home'}')">tcf<span>·</span>atelier</button><div class="nav-actions">${!minimal?`<button class="nav-link" onclick="go('home')">Features</button><button class="nav-link" onclick="document.querySelector('#pricing')?.scrollIntoView()">Pricing</button>`:''}${state.user?`<button class="nav-link" onclick="go('dashboard')">Dashboard</button><button class="nav-link" onclick="logout()">Sign out</button>`:`<button class="btn" onclick="go('auth')">Sign in</button>`}<button class="icon-btn" onclick="toggleTheme()" aria-label="Toggle theme">${state.theme==='dark'?'☀':'☾'}</button></div></nav>`}
function home(){return `<div class="shell">${nav()}<main><section class="hero"><div><div class="eyebrow">The focused route to your TCF score</div><h1>French practice,<br><em>without the noise.</em></h1><p class="lede">Forty full-length TCF practice tests, clear explanations, and a calmer way to build exam confidence — from your first A1 question to C1.</p><div class="hero-actions"><button class="btn" onclick="startDemo()">Start practicing →</button><button class="btn secondary" onclick="document.querySelector('#features').scrollIntoView()">See how it works</button></div><div class="mini-proof"><span>✓ 40 full tests</span><span>✓ Instant explanations</span><span>✓ Real score tracking</span></div></div><div class="preview"><div class="preview-top"><span class="mono">Review mode</span><span>03 / 39</span></div><div class="question-card"><span class="level">A1</span><div class="passage">Le train pour Lyon partira exceptionnellement voie 8.</div><div class="choice">A. Acheter un billet</div><div class="choice active">B. Changer de quai</div><div class="choice">C. Appeler un taxi</div></div></div></section><div class="stats-strip"><div class="stat"><strong>40</strong><span>curated practice tests</span></div><div class="stat"><strong>699</strong><span>CRS score mapping</span></div><div class="stat"><strong>2</strong><span>practice modes</span></div></div><section class="section" id="features"><div class="section-head"><div><div class="eyebrow">A complete practice room</div><h2>Learn from every answer.</h2></div><p class="section-copy">Train under pressure or slow things down. Every session builds a clear picture of where you are and what to do next.</p></div><div class="feature-grid">${[['01','Listen','Exam-style audio prompts and transcripts.'],['02','Read','Authentic notices, messages, and longer texts.'],['03','Write','Structured prompts from A1 through C1.'],['04','Speak','Guided scenarios with timed preparation.']].map(x=>`<article class="feature"><span class="num">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></section><section class="section" id="pricing"><div class="pricing"><div><div class="eyebrow">Simple access, no subscription</div><h2>Pick the time you need.</h2><p style="opacity:.7;line-height:1.7">All plans unlock every module, explanation, transcript and progress report.</p></div><div class="price-cards">${[['7 days','$10'],['15 days','$25'],['30 days','$45']].map((x,i)=>`<div class="price-card ${i===2?'best':''}"><div><small>${x[0]}</small><strong>${x[1]}</strong></div><button class="btn" onclick="checkout('${x[0]}','${x[1]}')">Choose</button></div>`).join('')}</div></div></section></main></div>`}
function auth(){return `<div class="shell">${nav(true)}<div class="auth-wrap"><form class="auth-card" onsubmit="login(event)"><div class="eyebrow">Welcome to your study room</div><h1>Continue your progress.</h1><p class="user-note">Sign in or create an account — it only takes a moment.</p><button type="button" class="btn google" onclick="googleLogin()">G&nbsp;&nbsp; Continue with Google</button><div class="divider">OR WITH EMAIL</div><div class="field"><label>Email address</label><input id="email" type="email" required placeholder="you@example.com"></div><div class="field"><label>Password</label><input type="password" required minlength="6" placeholder="At least 6 characters"></div><button class="btn" style="width:100%;margin-top:22px">Continue →</button></form></div></div>`}
function dashboard(){if(!state.user)return auth();return `<div class="shell">${nav()}<main class="dashboard"><div class="welcome"><div><div class="eyebrow">Your learning room</div><h1>Welcome back.</h1><p class="user-note">${state.user.email}</p></div><button class="btn secondary" onclick="go('tests')">Resume practice →</button></div><div class="chart"><span class="chart-label">SCORE TREND · LAST 5 ATTEMPTS</span><div class="chart-grid"><i class="chart-line"></i></div></div><div class="section-head"><div><div class="eyebrow">Practice</div><h2 style="font-size:40px">Choose a skill</h2></div><p class="section-copy">Forty tests in every module, arranged from A1 to C1.</p></div><div class="module-grid">${[['◖','Listening','Audio comprehension'],['▤','Reading','Text comprehension'],['✎','Writing','Guided production'],['◉','Speaking','Oral production']].map(x=>`<button class="module" onclick="openModule('${x[1]}')"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div></main></div>`}
function tests(){return `<div class="shell">${nav()}<main class="dashboard"><div class="tests-head"><div><div class="eyebrow">${state.module} practice</div><h1>${state.module} Tests</h1><p class="user-note">40 full tests · all levels · three attempts each</p></div><button class="btn secondary" onclick="go('dashboard')">← Dashboard</button></div><div class="chart" style="height:190px"><span class="chart-label">SCORE TREND</span><div class="chart-grid"><i class="chart-line"></i></div></div><div class="tests-grid">${Array.from({length:40},(_,i)=>`<button class="test ${i===0?'done':''}" onclick="chooseTest(${i+1})"><small>Test</small>${i+1}${i===0?'<small>✓ demo</small>':''}</button>`).join('')}</div></main></div>`}
function modeModal(){return `<div class="modal-backdrop" onclick="if(event.target===this)render()"><div class="modal"><div class="eyebrow">Choose your mode</div><h2 style="font-size:40px;margin:8px 0 22px">How do you want to practice?</h2><button class="mode" onclick="beginExam('exam')"><h3>⏱ Exam Mode <span class="level">35 minutes</span></h3><p>39 questions under timed conditions. No answers or explanations until the end.</p></button><button class="mode" onclick="beginExam('review')"><h3>▤ Review Mode <span class="level">No timer</span></h3><p>Go at your pace. See the correct answer and explanation after each response.</p></button><button class="btn ghost" style="width:100%" onclick="render()">Cancel</button></div></div>`}
function exam(){const q=questions[state.q%questions.length],selected=state.answers[state.q];return `<div class="shell">${nav(true)}<div class="progress"><i style="width:${((state.q+1)/questions.length)*100}%"></i></div><main class="exam"><aside class="rail"><div class="rail-top"><b>${state.module} · Test ${state.test}</b><p class="user-note">${Object.keys(state.answers).length}/${questions.length} answered</p></div><div class="q-nav">${questions.map((_,i)=>`<button class="q-dot ${i===state.q?'active':''}" onclick="jump(${i})">Q${i+1}</button>`).join('')}</div></aside><section class="exam-main"><div class="exam-top"><span class="level">${q.level}</span><span class="mono">Q${state.q+1}/${questions.length} ${state.mode==='exam'?' · 34:42':''}</span></div><div class="prompt">${q.prompt.replace(/\n/g,'<br>')}</div><h3>${q.ask}</h3><div class="answers">${q.answers.map((a,i)=>{let cls=selected===i?'selected':'';if(state.mode==='review'&&selected!==undefined)cls+=i===q.correct?' correct':selected===i?' wrong':'';return `<button class="answer ${cls}" onclick="answer(${i})"><b>${'ABCD'[i]}.</b>&nbsp;&nbsp;${a}</button>`}).join('')}</div>${state.mode==='review'&&selected!==undefined?`<p class="user-note" style="margin-top:18px">${selected===q.correct?'Correct — well read.':'The key detail in the prompt points to answer '+ 'ABCD'[q.correct]+'.'}</p>`:''}<div class="exam-actions"><button class="btn ghost" onclick="flag()">${state.flagged.has(state.q)?'⚑ Flagged':'⚐ Flag for review'}</button><button class="btn" onclick="next()">${state.q===questions.length-1?'Finish test':'Confirm & next →'}</button></div></section></main></div>`}
function results(){let correct=0;questions.forEach((q,i)=>{if(state.answers[i]===q.correct)correct++});const answered=Object.keys(state.answers).length;return `<div class="shell">${nav()}<main class="dashboard"><div class="result-card"><div class="eyebrow">Test ${state.test} · ${state.mode} mode</div><h1 style="font-size:52px;margin-bottom:0">Test complete.</h1><div class="score">${answered?Math.round(correct/answered*100):0}%</div><p class="user-note">of answered questions</p><div class="score-grid"><div><strong style="color:var(--green)">${correct}</strong><small>correct</small></div><div><strong style="color:var(--red)">${answered-correct}</strong><small>wrong</small></div><div><strong>${questions.length-answered}</strong><small>skipped</small></div></div><div style="text-align:left"><span class="mono user-note">TCF score estimate · ${Math.round(correct/questions.length*699)} pts</span><div class="level-bar"></div></div><h2 style="font-size:36px">Estimated level: ${correct/questions.length>.8?'B2':correct/questions.length>.55?'B1':'A2'}</h2><div class="hero-actions" style="justify-content:center"><button class="btn secondary" onclick="retry()">Retry test</button><button class="btn" onclick="go('tests')">All tests →</button></div></div></main></div>`}
function render(){state.route=location.hash.slice(1)||'home';const views={home,auth,dashboard,tests,exam,results};app.innerHTML=(views[state.route]||home)();setTheme()}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';setTheme();render()}
function startDemo(){if(!state.user)go('auth');else go('dashboard')}
function login(e){e.preventDefault();saveUser(document.querySelector('#email').value)}
function googleLogin(){saveUser('learner@gmail.com');toast('Demo Google account connected')}
function saveUser(email){state.user={email};localStorage.setItem('tcf-user',JSON.stringify(state.user));go('dashboard')}
function logout(){state.user=null;localStorage.removeItem('tcf-user');go('home')}
function openModule(name){state.module=name;go('tests')}
function chooseTest(n){state.test=n;app.insertAdjacentHTML('beforeend',modeModal())}
function beginExam(mode){state.mode=mode;state.q=0;state.answers={};state.flagged.clear();go('exam')}
function answer(i){state.answers[state.q]=i;render()}
function jump(i){state.q=i;render()}
function next(){if(state.q<questions.length-1){state.q++;render()}else go('results')}
function flag(){state.flagged.has(state.q)?state.flagged.delete(state.q):state.flagged.add(state.q);render()}
function retry(){state.answers={};state.q=0;go('exam')}
function checkout(days,price){toast(`${days} plan (${price}) — Razorpay checkout ready for API keys`)}
window.addEventListener('hashchange',render);setTheme();render();
